name: Create message

on:
  workflow_dispatch:
    inputs:
      config:
        description: Message config
        required: true

concurrency:
  group: default
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.BACKEND_REPO }}
          token: ${{ secrets.BACKEND_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download release assets
        env:
          RELEASE_URL: https://github.com/${{ github.repository }}/releases/download/${{ vars.RELEASE_TAG }}/output.json
        run: |
          wget -O output.json "$RELEASE_URL"

      - name: Run script
        env:
          PROG_INPUT: ${{ github.event.inputs.config }}
        run: |
          python message.py

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          overwrite_files: true
          tag_name: ${{ vars.RELEASE_TAG }}
          fail_on_unmatched_files: true
          files: |
            output.json
